### ISSUE TITLE
pipによるインストール時にsetup.pyでエラー

### ISSUE THREAD

**Issue by betasewer** [betasewer/machaon#4]
あるＰＣでのみ発生するエラー。

同一の問題を発見。
https://github.com/moremoban/pypi-mobans/issues/37
そのＰＣで使われるsetuptoolsのバージョンが古すぎることに起因？

```
pip install git+http://github.com/betasewer/machaon --upgrade

Collecting git+http://github.com/betasewer/machaon
  Cloning http://github.com/betasewer/machaon to /private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-req-build-js1005fg
  Running command git clone -q http://github.com/betasewer/machaon /private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-req-build-js1005fg
Building wheels for collected packages: machaon
  Building wheel for machaon (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/Cellar/python/3.6.2/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-req-build-js1005fg/setup.py'"'"'; __file__='"'"'/private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-req-build-js1005fg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-wheel-yzke0t7x --python-tag cp36
       cwd: /private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-req-build-js1005fg/
  Complete output (116 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/machaon
  ...
  Copying machaon.egg-info to build/bdist.macosx-10.9-x86_64/wheel/machaon-0.0.8.0-py3.6.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/xt/ydxgsgk57cgd_mx6sxf_5whm0000gn/T/pip-req-build-js1005fg/setup.py", line 55, in <module>
      'Topic :: Software Development :: Libraries :: Python Modules',
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 399, in egg2dist
      distribution=self.distribution)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wheel/metadata.py", line 176, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wheel/metadata.py", line 231, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2918, in parse
      req, = parse_requirements(s)
  ValueError: not enough values to unpack (expected 1, got 0)
  ----------------------------------------
  ERROR: Failed building wheel for machaon
  Running setup.py clean for machaon
Failed to build machaon
```

**Comment by betasewer** [comment]
requirements.txtに空行があることが直接の原因。
wheel のバージョンが0.31.0より前で、Metadataがバージョン 2.0（PEP 426）の時に発生すると思われる。

**Comment by betasewer** [comment]
そのPCのwheelをpipから更新して解決。
